### ISSUE TITLE
Pasargad Bank endpoint working 😳😳!

### ISSUE THREAD

**Issue by javadnikbakht** [herotux/shabayab#3]
Why the endpoint for Pasargad Bank working ?? There is not any function for that in app.In addition, it does not work properly for lots of accounts number 😐😐.

**Comment by herotux** [comment]
because we have func for pasargad 

https://github.com/herotux/shabayab/blob/af64ed3d1b272991230934df76981a58e7080489/app.py#L419

**Comment by javadnikbakht** [comment]
Ooops, the new changes were not loaded for me. Ok let's see these accounts and their iban:


Acc number: 415.110.12279892.1
True Iban: IR050570041511012279892001
shabayab: IR050570041511012279892001

Acc number: 207.11.240721.1
True Iban:IR950570020701100240721001
shabayab: IR880570020711240721001

Acc number: 256.11.899.899.1
True Iban: IR020570025601100899899001
shabayab: IR610570025611899899001


All these accounts mentioned above are related to Pasargad Bank

**Comment by herotux** [comment]
I think the accounts of this bank are separated by a sub-line and should be calculated according to that night, but regardless of this issue and I have calculated with the character, I have to solve it very soon. Thank you for reporting this bug.

**Comment by javadnikbakht** [comment]
I think it would be better to write tests to check all of Shabayab endpoints after writing required functions for all banks  to check the functionality related to each bank.How do you think?
